service: serverless-rest-api-with-dynamodb

frameworkVersion: ">=1.1.0 <=2.16.1"

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  profile: serverless-admin
  environment:
    DYNAMODB_TABLE: reviews
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: reviews/create.create
    events:
      - http:
          path: reviews
          method: post
          cors: true

  list:
    handler: reviews/list.list
    events:
      - http:
          path: reviews
          method: get
          cors: true

  get:
    handler: reviews/get.get
    events:
      - http:
          path: reviews/{id}
          method: get
          cors: true

  update:
    handler: reviews/update.update
    events:
      - http:
          path: reviews/{id}
          method: put
          cors: true

  delete:
    handler: reviews/delete.delete
    events:
      - http:
          path: reviews/{id}
          method: delete
          cors: true

resources:
  Resources:
    ReviewsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
